import type { Metadata } from "next";
import { AppProps } from "next/app";
import { useEffect } from 'react';
// import localFont from "next/font/local";
import { geistMono, poppins } from "../utils/fonts";
import '@/styles/globals.css';
import WebLayout from "@/layouts/webLayout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function MyApp({ Component, pageProps }: AppProps) {
    useEffect(() => {
        if ('serviceWorker' in navigator) {
            navigator.serviceWorker.register('/sw.js').catch(() => { });
        }
    }, []);

    return (
        <div className={`${poppins.className} ${geistMono.variable} antialiased`}>
            <WebLayout>
                <Component {...pageProps} />
            </WebLayout>
        </div>
    );
}